
2022-09-21 15:21:24,698 : root : INFO : Serving Flask app 'contacts'
2022-09-21 15:21:24,699 : root : INFO : Debug mode: off
2022-09-21 15:21:24,699 : root : WARNING : This is a development server. Do not use it in a production deployment. Use a production WSGI server instead
2022-09-21 15:21:24,699 : root : INFO : Running on http://127.0.0.1:5000
2022-09-21 15:21:24,706 : werkzeug : INFO : [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2022-09-21 15:21:24,706 : werkzeug : INFO : [33mPress CTRL+C to quit[0m
2022-09-21 15:21:39,170 : root : ERROR : Page not found, http://localhost:5000/omar is a wrong url 400-
2022-09-21 15:21:39,231 : werkzeug : INFO : 127.0.0.1 - - [21/Sep/2022 15:21:39] "[33mGET /omar HTTP/1.1[0m" 404 -
2022-09-21 15:22:07,414 : root : INFO : Running on http://127.0.0.1:5000/contacts/50 (One Contact Page) 200-
2022-09-21 15:22:07,416 : werkzeug : INFO : 127.0.0.1 - - [21/Sep/2022 15:22:07] "GET /contacts/50 HTTP/1.1" 200 -
2022-09-21 15:23:03,330 : root : INFO : Running on http://127.0.0.1:5000/contacts/2 (One Contact Page) 200-
2022-09-21 15:23:03,333 : werkzeug : INFO : 127.0.0.1 - - [21/Sep/2022 15:23:03] "GET /contacts/2 HTTP/1.1" 200 -
2022-09-21 15:23:04,291 : root : INFO : Running on http://127.0.0.1:5000/contacts/2,1 (One Contact Page) 200-
2022-09-21 15:23:04,292 : contacts : ERROR : Exception on /contacts/2,1 [GET]
Traceback (most recent call last):
  File "C:\Users\omare\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\omare\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\omare\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask_restful\__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "C:\Users\omare\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "C:\Users\omare\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask_restful\__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "contacts.py", line 98, in get
    if contact["id"] == int(id):
ValueError: invalid literal for int() with base 10: '2,1'
2022-09-21 15:23:04,295 : werkzeug : INFO : 127.0.0.1 - - [21/Sep/2022 15:23:04] "[35m[1mGET /contacts/2,1 HTTP/1.1[0m" 500 -
2022-09-21 15:26:03,965 : root : INFO : Running on http://127.0.0.1:5000/contacts/1 (One Contact Page) 200-
2022-09-21 15:26:03,967 : werkzeug : INFO : 127.0.0.1 - - [21/Sep/2022 15:26:03] "GET /contacts/1 HTTP/1.1" 200 -
2022-09-21 15:26:24,135 : root : INFO : Running on http://127.0.0.1:5000/contacts/2 (One Contact Page) 200-
2022-09-21 15:26:24,136 : werkzeug : INFO : 127.0.0.1 - - [21/Sep/2022 15:26:24] "GET /contacts/2 HTTP/1.1" 200 -
2022-09-21 15:28:10,425 : root : INFO : Serving Flask app 'contacts'
2022-09-21 15:28:10,425 : root : INFO : Debug mode: off
2022-09-21 15:28:10,425 : root : WARNING : This is a development server. Do not use it in a production deployment. Use a production WSGI server instead
2022-09-21 15:28:10,425 : root : INFO : Running on http://127.0.0.1:5000
2022-09-21 15:28:10,432 : werkzeug : INFO : [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2022-09-21 15:28:10,432 : werkzeug : INFO : [33mPress CTRL+C to quit[0m
2022-09-21 15:28:16,740 : root : INFO : Running on http://127.0.0.1:5000/contacts/50 (One Contact Page) 200-
2022-09-21 15:28:16,743 : werkzeug : INFO : 127.0.0.1 - - [21/Sep/2022 15:28:16] "GET /contacts/50 HTTP/1.1" 200 -
2022-09-21 15:30:43,569 : root : INFO : Serving Flask app 'contacts'
2022-09-21 15:30:43,569 : root : INFO : Debug mode: off
2022-09-21 15:30:43,569 : root : WARNING : This is a development server. Do not use it in a production deployment. Use a production WSGI server instead
2022-09-21 15:30:43,570 : root : INFO : Running on http://127.0.0.1:5000
2022-09-21 15:30:43,576 : werkzeug : INFO : [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2022-09-21 15:30:43,576 : werkzeug : INFO : [33mPress CTRL+C to quit[0m
2022-09-21 15:31:13,428 : root : INFO : Serving Flask app 'contacts'
2022-09-21 15:31:13,428 : root : INFO : Debug mode: off
2022-09-21 15:31:13,428 : root : WARNING : This is a development server. Do not use it in a production deployment. Use a production WSGI server instead
2022-09-21 15:31:13,428 : root : INFO : Running on http://127.0.0.1:5000
2022-09-21 15:31:13,428 : root : DEBUG : OMAR
2022-09-21 15:31:13,434 : werkzeug : INFO : [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2022-09-21 15:31:13,434 : werkzeug : INFO : [33mPress CTRL+C to quit[0m
2022-09-21 15:31:38,199 : root : DEBUG : ID = 2
2022-09-21 15:31:38,199 : root : INFO : Running on http://127.0.0.1:5000/contacts/2 (One Contact Page) 200-
2022-09-21 15:31:38,201 : root : DEBUG : Contacts = [{'id': 0, 'fname': 'Omar', 'lname': 'El-Meteny', 'number': '01012062866'}, {'id': 1, 'fname': 'Kareem', 'lname': 'El-Meteny', 'number': '01012062866'}, {'id': 2, 'fname': 'Sherif', 'lname': 'El-Meteny', 'number': '01012062866'}, {'id': 3, 'fname': 'maha', 'lname': 'heshmat', 'number': '01006625354'}, {'id': 5, 'fname': 'ahmed', 'lname': 'shoukry', 'number': '01008877651'}, {'id': 6, 'fname': 'omar', 'lname': 'sherif', 'number': '01012062866'}, {'id': 7, 'fname': 'kareem', 'lname': 'sherif', 'number': '01012062866'}]
2022-09-21 15:31:38,202 : root : DEBUG : C = 0
2022-09-21 15:31:38,202 : root : DEBUG : C = 1
2022-09-21 15:31:38,202 : root : DEBUG : C = 2
2022-09-21 15:31:38,202 : root : DEBUG : Result = {'id': 2, 'fname': 'Sherif', 'lname': 'El-Meteny', 'number': '01012062866'}
2022-09-21 15:31:38,203 : werkzeug : INFO : 127.0.0.1 - - [21/Sep/2022 15:31:38] "GET /contacts/2 HTTP/1.1" 200 -
2022-09-21 15:32:51,770 : root : DEBUG : ID = 1
2022-09-21 15:32:51,770 : root : INFO : Running on http://127.0.0.1:5000/contacts/1 (One Contact Page) 200-
2022-09-21 15:32:51,771 : root : DEBUG : Contacts = [{'id': 0, 'fname': 'Omar', 'lname': 'El-Meteny', 'number': '01012062866'}, {'id': 1, 'fname': 'Kareem', 'lname': 'El-Meteny', 'number': '01012062866'}, {'id': 2, 'fname': 'Sherif', 'lname': 'El-Meteny', 'number': '01012062866'}, {'id': 3, 'fname': 'maha', 'lname': 'heshmat', 'number': '01006625354'}, {'id': 5, 'fname': 'ahmed', 'lname': 'shoukry', 'number': '01008877651'}, {'id': 6, 'fname': 'omar', 'lname': 'sherif', 'number': '01012062866'}, {'id': 7, 'fname': 'kareem', 'lname': 'sherif', 'number': '01012062866'}]
2022-09-21 15:32:51,772 : root : DEBUG : C = 0
2022-09-21 15:32:51,772 : root : DEBUG : C = 1
2022-09-21 15:32:51,772 : root : DEBUG : Result = {'id': 1, 'fname': 'Kareem', 'lname': 'El-Meteny', 'number': '01012062866'}
2022-09-21 15:32:51,773 : werkzeug : INFO : 127.0.0.1 - - [21/Sep/2022 15:32:51] "GET /contacts/1 HTTP/1.1" 200 -
2022-09-21 15:32:52,671 : root : DEBUG : ID = 1,2
2022-09-21 15:32:52,671 : root : INFO : Running on http://127.0.0.1:5000/contacts/1,2 (One Contact Page) 200-
2022-09-21 15:32:52,671 : root : DEBUG : Contacts = [{'id': 0, 'fname': 'Omar', 'lname': 'El-Meteny', 'number': '01012062866'}, {'id': 1, 'fname': 'Kareem', 'lname': 'El-Meteny', 'number': '01012062866'}, {'id': 2, 'fname': 'Sherif', 'lname': 'El-Meteny', 'number': '01012062866'}, {'id': 3, 'fname': 'maha', 'lname': 'heshmat', 'number': '01006625354'}, {'id': 5, 'fname': 'ahmed', 'lname': 'shoukry', 'number': '01008877651'}, {'id': 6, 'fname': 'omar', 'lname': 'sherif', 'number': '01012062866'}, {'id': 7, 'fname': 'kareem', 'lname': 'sherif', 'number': '01012062866'}]
2022-09-21 15:32:52,671 : root : DEBUG : C = 0
2022-09-21 15:32:52,671 : contacts : ERROR : Exception on /contacts/1,2 [GET]
Traceback (most recent call last):
  File "C:\Users\omare\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\omare\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\omare\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask_restful\__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "C:\Users\omare\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "C:\Users\omare\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask_restful\__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "contacts.py", line 98, in get
    logging.debug("Result = " + str(contact))
ValueError: invalid literal for int() with base 10: '1,2'
2022-09-21 15:32:52,674 : werkzeug : INFO : 127.0.0.1 - - [21/Sep/2022 15:32:52] "[35m[1mGET /contacts/1,2 HTTP/1.1[0m" 500 -
2022-09-21 15:36:59,170 : root : DEBUG : ID = all
2022-09-21 15:36:59,170 : root : INFO : Running on http://127.0.0.1:5000/contacts/all (All Contacts Page) 200-
2022-09-21 15:36:59,171 : root : DEBUG : Contacts = [{'id': 0, 'fname': 'Omar', 'lname': 'El-Meteny', 'number': '01012062866'}, {'id': 1, 'fname': 'Kareem', 'lname': 'El-Meteny', 'number': '01012062866'}, {'id': 2, 'fname': 'Sherif', 'lname': 'El-Meteny', 'number': '01012062866'}, {'id': 3, 'fname': 'maha', 'lname': 'heshmat', 'number': '01006625354'}, {'id': 5, 'fname': 'ahmed', 'lname': 'shoukry', 'number': '01008877651'}, {'id': 6, 'fname': 'omar', 'lname': 'sherif', 'number': '01012062866'}, {'id': 7, 'fname': 'kareem', 'lname': 'sherif', 'number': '01012062866'}]
2022-09-21 15:36:59,173 : werkzeug : INFO : 127.0.0.1 - - [21/Sep/2022 15:36:59] "GET /contacts/all HTTP/1.1" 200 -
2022-09-21 15:37:26,763 : root : DEBUG : ID = e
2022-09-21 15:37:26,763 : root : INFO : Running on http://127.0.0.1:5000/contacts/e (One Contact Page) 200-
2022-09-21 15:37:26,764 : root : DEBUG : Contacts = [{'id': 0, 'fname': 'Omar', 'lname': 'El-Meteny', 'number': '01012062866'}, {'id': 1, 'fname': 'Kareem', 'lname': 'El-Meteny', 'number': '01012062866'}, {'id': 2, 'fname': 'Sherif', 'lname': 'El-Meteny', 'number': '01012062866'}, {'id': 3, 'fname': 'maha', 'lname': 'heshmat', 'number': '01006625354'}, {'id': 5, 'fname': 'ahmed', 'lname': 'shoukry', 'number': '01008877651'}, {'id': 6, 'fname': 'omar', 'lname': 'sherif', 'number': '01012062866'}, {'id': 7, 'fname': 'kareem', 'lname': 'sherif', 'number': '01012062866'}]
2022-09-21 15:37:26,764 : root : DEBUG : C = 0
2022-09-21 15:37:26,764 : contacts : ERROR : Exception on /contacts/e [GET]
Traceback (most recent call last):
  File "C:\Users\omare\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\omare\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\omare\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask_restful\__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "C:\Users\omare\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "C:\Users\omare\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask_restful\__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "contacts.py", line 98, in get
    logging.debug("Result = " + str(contact))
ValueError: invalid literal for int() with base 10: 'e'
2022-09-21 15:37:26,765 : werkzeug : INFO : 127.0.0.1 - - [21/Sep/2022 15:37:26] "[35m[1mGET /contacts/e HTTP/1.1[0m" 500 -
2022-09-21 15:39:55,949 : root : INFO : Serving Flask app 'contacts'
2022-09-21 15:39:55,949 : root : INFO : Debug mode: off
2022-09-21 15:39:55,949 : root : WARNING : This is a development server. Do not use it in a production deployment. Use a production WSGI server instead
2022-09-21 15:39:55,949 : root : INFO : Running on http://127.0.0.1:5000
2022-09-21 15:39:55,956 : werkzeug : INFO : [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2022-09-21 15:39:55,956 : werkzeug : INFO : [33mPress CTRL+C to quit[0m
2022-09-21 15:39:59,827 : root : DEBUG : ID = e
2022-09-21 15:39:59,827 : contacts : ERROR : Exception on /contacts/e [GET]
Traceback (most recent call last):
  File "C:\Users\omare\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\omare\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\omare\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask_restful\__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "C:\Users\omare\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "C:\Users\omare\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask_restful\__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "contacts.py", line 87, in get
    elif int(id) >= 0:
ValueError: invalid literal for int() with base 10: 'e'
2022-09-21 15:39:59,835 : werkzeug : INFO : 127.0.0.1 - - [21/Sep/2022 15:39:59] "[35m[1mGET /contacts/e HTTP/1.1[0m" 500 -
2022-09-21 15:40:55,529 : root : DEBUG : ID = id
2022-09-21 15:40:55,529 : contacts : ERROR : Exception on /contacts/id [GET]
Traceback (most recent call last):
  File "C:\Users\omare\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\omare\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\omare\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask_restful\__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "C:\Users\omare\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "C:\Users\omare\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask_restful\__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "contacts.py", line 87, in get
    elif int(id) >= 0:
ValueError: invalid literal for int() with base 10: 'id'
2022-09-21 15:40:55,530 : werkzeug : INFO : 127.0.0.1 - - [21/Sep/2022 15:40:55] "[35m[1mGET /contacts/id?=2 HTTP/1.1[0m" 500 -
2022-09-21 15:41:18,903 : root : DEBUG : ID = 50
2022-09-21 15:41:18,903 : root : INFO : Running on http://127.0.0.1:5000/contacts/50 (One Contact Page) 200-
2022-09-21 15:41:18,905 : root : DEBUG : Contacts = [{'id': 0, 'fname': 'Omar', 'lname': 'El-Meteny', 'number': '01012062866'}, {'id': 1, 'fname': 'Kareem', 'lname': 'El-Meteny', 'number': '01012062866'}, {'id': 2, 'fname': 'Sherif', 'lname': 'El-Meteny', 'number': '01012062866'}, {'id': 3, 'fname': 'maha', 'lname': 'heshmat', 'number': '01006625354'}, {'id': 5, 'fname': 'ahmed', 'lname': 'shoukry', 'number': '01008877651'}, {'id': 6, 'fname': 'omar', 'lname': 'sherif', 'number': '01012062866'}, {'id': 7, 'fname': 'kareem', 'lname': 'sherif', 'number': '01012062866'}]
2022-09-21 15:41:18,905 : root : DEBUG : ID = 0
2022-09-21 15:41:18,906 : root : DEBUG : ID = 1
2022-09-21 15:41:18,906 : root : DEBUG : ID = 2
2022-09-21 15:41:18,906 : root : DEBUG : ID = 3
2022-09-21 15:41:18,906 : root : DEBUG : ID = 5
2022-09-21 15:41:18,907 : root : DEBUG : ID = 6
2022-09-21 15:41:18,907 : root : DEBUG : ID = 7
2022-09-21 15:41:18,908 : werkzeug : INFO : 127.0.0.1 - - [21/Sep/2022 15:41:18] "GET /contacts/50 HTTP/1.1" 200 -
2022-09-21 15:42:25,072 : root : DEBUG : ID = 1
2022-09-21 15:42:25,072 : root : INFO : Running on http://127.0.0.1:5000/contacts/1 (One Contact Page) 200-
2022-09-21 15:42:25,073 : root : DEBUG : Contacts = [{'id': 0, 'fname': 'Omar', 'lname': 'El-Meteny', 'number': '01012062866'}, {'id': 1, 'fname': 'Kareem', 'lname': 'El-Meteny', 'number': '01012062866'}, {'id': 2, 'fname': 'Sherif', 'lname': 'El-Meteny', 'number': '01012062866'}, {'id': 3, 'fname': 'maha', 'lname': 'heshmat', 'number': '01006625354'}, {'id': 5, 'fname': 'ahmed', 'lname': 'shoukry', 'number': '01008877651'}, {'id': 6, 'fname': 'omar', 'lname': 'sherif', 'number': '01012062866'}, {'id': 7, 'fname': 'kareem', 'lname': 'sherif', 'number': '01012062866'}]
2022-09-21 15:42:25,073 : root : DEBUG : ID = 0
2022-09-21 15:42:25,074 : root : DEBUG : ID = 1
2022-09-21 15:42:25,074 : root : DEBUG : Result = {'id': 1, 'fname': 'Kareem', 'lname': 'El-Meteny', 'number': '01012062866'}
2022-09-21 15:42:25,075 : werkzeug : INFO : 127.0.0.1 - - [21/Sep/2022 15:42:25] "GET /contacts/1 HTTP/1.1" 200 -
2022-09-21 15:42:41,165 : root : INFO : Serving Flask app 'contacts'
2022-09-21 15:42:41,165 : root : INFO : Debug mode: off
2022-09-21 15:42:41,165 : root : WARNING : This is a development server. Do not use it in a production deployment. Use a production WSGI server instead
2022-09-21 15:42:41,165 : root : INFO : Running on http://127.0.0.1:5000
2022-09-21 15:42:41,172 : werkzeug : INFO : [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2022-09-21 15:42:41,172 : werkzeug : INFO : [33mPress CTRL+C to quit[0m
2022-09-21 15:42:43,399 : root : DEBUG : ID = 1
2022-09-21 15:42:43,399 : root : INFO : Running on http://127.0.0.1:5000/contacts/1 (One Contact Page) 200-
2022-09-21 15:42:43,400 : root : DEBUG : Contacts = [{'id': 0, 'fname': 'Omar', 'lname': 'El-Meteny', 'number': '01012062866'}, {'id': 1, 'fname': 'Kareem', 'lname': 'El-Meteny', 'number': '01012062866'}, {'id': 2, 'fname': 'Sherif', 'lname': 'El-Meteny', 'number': '01012062866'}, {'id': 3, 'fname': 'maha', 'lname': 'heshmat', 'number': '01006625354'}, {'id': 5, 'fname': 'ahmed', 'lname': 'shoukry', 'number': '01008877651'}, {'id': 6, 'fname': 'omar', 'lname': 'sherif', 'number': '01012062866'}, {'id': 7, 'fname': 'kareem', 'lname': 'sherif', 'number': '01012062866'}]
2022-09-21 15:42:43,401 : contacts : ERROR : Exception on /contacts/1 [GET]
Traceback (most recent call last):
  File "C:\Users\omare\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\omare\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\omare\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask_restful\__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "C:\Users\omare\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "C:\Users\omare\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask_restful\__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "contacts.py", line 95, in get
    logging.debug("Contact = " + contact)
TypeError: can only concatenate str (not "dict") to str
2022-09-21 15:42:43,407 : werkzeug : INFO : 127.0.0.1 - - [21/Sep/2022 15:42:43] "[35m[1mGET /contacts/1 HTTP/1.1[0m" 500 -
2022-09-21 15:42:59,832 : root : DEBUG : ID = 2
2022-09-21 15:42:59,832 : root : INFO : Running on http://127.0.0.1:5000/contacts/2 (One Contact Page) 200-
2022-09-21 15:42:59,833 : root : DEBUG : Contacts = [{'id': 0, 'fname': 'Omar', 'lname': 'El-Meteny', 'number': '01012062866'}, {'id': 1, 'fname': 'Kareem', 'lname': 'El-Meteny', 'number': '01012062866'}, {'id': 2, 'fname': 'Sherif', 'lname': 'El-Meteny', 'number': '01012062866'}, {'id': 3, 'fname': 'maha', 'lname': 'heshmat', 'number': '01006625354'}, {'id': 5, 'fname': 'ahmed', 'lname': 'shoukry', 'number': '01008877651'}, {'id': 6, 'fname': 'omar', 'lname': 'sherif', 'number': '01012062866'}, {'id': 7, 'fname': 'kareem', 'lname': 'sherif', 'number': '01012062866'}]
2022-09-21 15:42:59,833 : contacts : ERROR : Exception on /contacts/2 [GET]
Traceback (most recent call last):
  File "C:\Users\omare\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\omare\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\omare\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask_restful\__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "C:\Users\omare\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "C:\Users\omare\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask_restful\__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "contacts.py", line 95, in get
    logging.debug("Contact = " + contact)
TypeError: can only concatenate str (not "dict") to str
2022-09-21 15:42:59,834 : werkzeug : INFO : 127.0.0.1 - - [21/Sep/2022 15:42:59] "[35m[1mGET /contacts/2 HTTP/1.1[0m" 500 -
2022-09-21 15:43:36,446 : root : INFO : Serving Flask app 'contacts'
2022-09-21 15:43:36,446 : root : INFO : Debug mode: off
2022-09-21 15:43:36,446 : root : WARNING : This is a development server. Do not use it in a production deployment. Use a production WSGI server instead
2022-09-21 15:43:36,446 : root : INFO : Running on http://127.0.0.1:5000
2022-09-21 15:43:36,453 : werkzeug : INFO : [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2022-09-21 15:43:36,454 : werkzeug : INFO : [33mPress CTRL+C to quit[0m
2022-09-21 15:43:39,225 : root : DEBUG : ID = 2
2022-09-21 15:43:39,225 : root : INFO : Running on http://127.0.0.1:5000/contacts/2 (One Contact Page) 200-
2022-09-21 15:43:39,227 : root : DEBUG : Contacts = [{'id': 0, 'fname': 'Omar', 'lname': 'El-Meteny', 'number': '01012062866'}, {'id': 1, 'fname': 'Kareem', 'lname': 'El-Meteny', 'number': '01012062866'}, {'id': 2, 'fname': 'Sherif', 'lname': 'El-Meteny', 'number': '01012062866'}, {'id': 3, 'fname': 'maha', 'lname': 'heshmat', 'number': '01006625354'}, {'id': 5, 'fname': 'ahmed', 'lname': 'shoukry', 'number': '01008877651'}, {'id': 6, 'fname': 'omar', 'lname': 'sherif', 'number': '01012062866'}, {'id': 7, 'fname': 'kareem', 'lname': 'sherif', 'number': '01012062866'}]
2022-09-21 15:43:39,227 : root : DEBUG : Contact = {'id': 0, 'fname': 'Omar', 'lname': 'El-Meteny', 'number': '01012062866'}
2022-09-21 15:43:39,228 : root : DEBUG : Contact = {'id': 1, 'fname': 'Kareem', 'lname': 'El-Meteny', 'number': '01012062866'}
2022-09-21 15:43:39,228 : root : DEBUG : Contact = {'id': 2, 'fname': 'Sherif', 'lname': 'El-Meteny', 'number': '01012062866'}
2022-09-21 15:43:39,228 : root : DEBUG : Result = {'id': 2, 'fname': 'Sherif', 'lname': 'El-Meteny', 'number': '01012062866'}
2022-09-21 15:43:39,230 : werkzeug : INFO : 127.0.0.1 - - [21/Sep/2022 15:43:39] "GET /contacts/2 HTTP/1.1" 200 -
2022-09-21 15:44:02,100 : root : ERROR : Page not found, http://localhost:5000/contact is a wrong url 400-
2022-09-21 15:44:02,100 : werkzeug : INFO : 127.0.0.1 - - [21/Sep/2022 15:44:02] "[33mGET /contact HTTP/1.1[0m" 404 -
2022-09-21 15:44:10,050 : root : ERROR : Page not found, http://localhost:5000/contacts is a wrong url 400-
2022-09-21 15:44:10,050 : werkzeug : INFO : 127.0.0.1 - - [21/Sep/2022 15:44:10] "[33mGET /contacts HTTP/1.1[0m" 404 -
2022-09-21 15:44:14,147 : root : DEBUG : ID = 2
2022-09-21 15:44:14,147 : root : INFO : Running on http://127.0.0.1:5000/contacts/2 (One Contact Page) 200-
2022-09-21 15:44:14,147 : root : DEBUG : Contacts = [{'id': 0, 'fname': 'Omar', 'lname': 'El-Meteny', 'number': '01012062866'}, {'id': 1, 'fname': 'Kareem', 'lname': 'El-Meteny', 'number': '01012062866'}, {'id': 2, 'fname': 'Sherif', 'lname': 'El-Meteny', 'number': '01012062866'}, {'id': 3, 'fname': 'maha', 'lname': 'heshmat', 'number': '01006625354'}, {'id': 5, 'fname': 'ahmed', 'lname': 'shoukry', 'number': '01008877651'}, {'id': 6, 'fname': 'omar', 'lname': 'sherif', 'number': '01012062866'}, {'id': 7, 'fname': 'kareem', 'lname': 'sherif', 'number': '01012062866'}]
2022-09-21 15:44:14,147 : root : DEBUG : Contact = {'id': 0, 'fname': 'Omar', 'lname': 'El-Meteny', 'number': '01012062866'}
2022-09-21 15:44:14,147 : root : DEBUG : Contact = {'id': 1, 'fname': 'Kareem', 'lname': 'El-Meteny', 'number': '01012062866'}
2022-09-21 15:44:14,147 : root : DEBUG : Contact = {'id': 2, 'fname': 'Sherif', 'lname': 'El-Meteny', 'number': '01012062866'}
2022-09-21 15:44:14,148 : root : DEBUG : Result = {'id': 2, 'fname': 'Sherif', 'lname': 'El-Meteny', 'number': '01012062866'}
2022-09-21 15:44:14,148 : werkzeug : INFO : 127.0.0.1 - - [21/Sep/2022 15:44:14] "GET /contacts/2 HTTP/1.1" 200 -
2022-09-21 15:44:17,866 : root : ERROR : Page not found, http://localhost:5000/contacts/ is a wrong url 400-
2022-09-21 15:44:17,866 : werkzeug : INFO : 127.0.0.1 - - [21/Sep/2022 15:44:17] "[33mGET /contacts/ HTTP/1.1[0m" 404 -
2022-09-21 15:44:29,712 : root : DEBUG : ID = w
2022-09-21 15:44:29,713 : contacts : ERROR : Exception on /contacts/w [GET]
Traceback (most recent call last):
  File "C:\Users\omare\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\omare\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\omare\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask_restful\__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "C:\Users\omare\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "C:\Users\omare\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask_restful\__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "contacts.py", line 87, in get
    elif int(id) >= 0:
ValueError: invalid literal for int() with base 10: 'w'
2022-09-21 15:44:29,717 : werkzeug : INFO : 127.0.0.1 - - [21/Sep/2022 15:44:29] "[35m[1mGET /contacts/w HTTP/1.1[0m" 500 -
